[package]
name = "wav-files-stats"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.48", features = ["derive"] }
hound = "3.5.1"
rayon = "1.11.0"
walkdir = "2.5.0"

[dev-dependencies]
tempfile = "3.23.0"
